language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
install:
  - pip install -r .travis/requirements_1.4.txt
  - pip install -r .travis/requirements_1.5.txt
  - pip install -r .travis/requirements_1.6.txt
script:
  - python -W error:"":"":0 testproject/manage.py test wiki --settings=testproject.settings.travis

